### ISSUE TITLE
GTM doesn't use the right event data

### ISSUE THREAD

**Issue by opolstianko** [Tealium/tealium-collect-gtm-template#1]
Hello, we have just noticed that in cases when events are fired asyncronously - there is no guarantee that event which triggered Tealium Collect Tag to Fire is necessarily the last element in dataLayer
Please check the example code bellow:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-N4F92TM');</script>
    <!-- End Google Tag Manager -->
</head>
<body>
<script>
    window.dataLayer = [];
    dataLayer.push({
        event: "that_should_not_be_tracked"
    })
</script>

</body>
</html>
```

Tealium tag is configured to execute on 'All Pages' trigger which means triggering on 'gtm.js' event. However, at the moment GTM SDK is loaded and Tealium Tag Executed, gtm.js is not the last element in the data layer, the last one will be 'that_should_not_be_tracked', that cause Tealium Tag to use data of 'that_should_not_be_tracked' (the last one in dataLayer array at the moment of Tealium firing)

Most likely caused by:
https://github.com/Tealium/tealium-collect-gtm-template/blob/58badb8d189cbe6da5ea5457b2e6b68cac5987a7/template.tpl#L141

Can be fixed by:
```javascript
  var eventId = copyFromDataLayer('gtm.uniqueEventId');
  var mergedData = dataLayer.filter(function(event){
    return event['gtm.uniqueEventId'] == eventId;
  })[0] || {};
```

Optionally we can use find() instead of filter() for improved performance, but IE doesn't support it

**Comment by opolstianko** [comment]
Please note, that this part will also need to be adjusted:
https://github.com/Tealium/tealium-collect-gtm-template/blob/58badb8d189cbe6da5ea5457b2e6b68cac5987a7/template.tpl#L144-L156

Simple check on event id should work:
```javascript
if (current['gtm.uniqueEventId'] === eventId) {
  break
}
```

**Comment by tygavin** [comment]
This makes sense to provide an option to restrict data to just the specific event.  Current design is "last one wins" with  the Merge Data from All Previous Events checkbox checked.

I am assuming most implementations will use the Merge Data from All Previous Events checkbox in the Tealium Collect tag configuration to grab the entire dataLayer history.  I think that is what most users expect -- data elements are unique for each event so there is no conflict.

It sounds like you are **not** using this checkbox?  (OR, you are using this checkbox, but have shared data attribute in both of the events?)

**Comment by opolstianko** [comment]
Hey, @tygavin 
I think you are not fully getting the point, there are cases when event which TRIGGERED the tag is not the LAST ONE in the dataLayer array, which result in tracking completely broken (at least because Tealium will use event_name of the last event in the dataLayer and because data is merged not from all PREVIOUS events but also from some FUTURE events )

To fix that you need to implement additional check by event unique Id for both passing actual even data and merging all the data from events added to the dataLayer BEFORE event which triggered the tag

**Comment by tygavin** [comment]
Thank you for these details.  I can reproduce the issue.  I'm testing the following as the fix.

```javascript
function mergePreviousData(dataLayer) {
  var eventId = data.gtmEventId,
    foundCurrent = false,
    mergedData = {};
  
  // Very simple 'merge' that ignores any events 'pushed' after the eventId that triggered this tag
  for (let d = dataLayer.length-1; d >= 0; d--) {
    let current = dataLayer[d],
      currentEventId = current['gtm.uniqueEventId']; 
    
    if (currentEventId === eventId) {
      foundCurrent = true;
      mergedData = current;
    } else if (foundCurrent) {   
      if (current.event === undefined || data.mergeAllPreviousEventData) {
        for (let i in current){
          if (mergedData[i] === undefined) {
            mergedData[i] = current[i];
          }
        }
      } else {
        break;
      }
    } else {
      log('ignore =', current); 
    }
  }
  return mergedData;
}
```

**Comment by tygavin** [comment]
Update released by GTM.  @opolstianko Thank you for reporting this issue and for providing detailed information.
